import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const root = new URL("../", import.meta.url);
const read = (path) => readFile(new URL(path, root), "utf8");

test("admin route survives hash navigation and auth redirects", async () => {
  const page = await read("app/page.tsx");
  assert.match(page, /hash\.startsWith\("#admin"\)/);
  assert.match(page, /URLSearchParams/);
  assert.match(page, /access_token=/);
  assert.match(page, /hashchange/);
});

test("admin uses protected Supabase access and has no public demo", async () => {
  const admin = await read("app/Admin.tsx");
  const supabase = await read("app/supabase.ts");
  assert.match(admin, /signInWithPassword/);
  assert.match(supabase, /ADMIN_EMAIL\s*=\s*"ribeiroleonardoti@gmail\.com"/);
  assert.match(admin, /admin_get_proposals/);
  assert.match(admin, /admin_update_cart_status/);
  assert.match(admin, /admin_set_artwork_available/);
  assert.match(admin, /Tornar disponível/);
  assert.match(admin, /function normalizePriceDraft/);
  assert.match(admin, /function priceDraftToCents/);
  assert.match(admin, /inputMode="decimal"/);
  assert.match(admin, /placeholder="0,00"/);
  assert.match(admin, /centavos\.padEnd\(2, "0"\)/);
  assert.match(admin, /groupByPerson/);
  assert.match(admin, /Intenções por pessoa/);
  assert.match(admin, /Fila de atendimento/);
  assert.ok(admin.indexOf('id="queue-title"') < admin.indexOf('id="pricing-title"'));
  assert.match(admin, /statusFilters\.map/);
  assert.match(admin, /className="people-list" tabIndex=\{people\.length > 4 \? 0 : undefined\} aria-label="Pessoas na fila de atendimento"/);
  assert.match(admin, /Histórico de intenções/);
  assert.match(admin, /tabIndex=\{person\.intents\.length > 2/);
  assert.match(admin, /<details className="person-card"/);
  assert.match(admin, /Ver detalhes/);
  assert.match(admin, /Contato direto/);
  assert.match(admin, /Somente o usuário autorizado e a senha fixa/);
  assert.match(admin, /className="admin-brand"/);
  assert.match(admin, /className="admin-brand-crest"/);
  assert.match(admin, /className="admin-header-actions"/);
  const css = await read("app/globals.css");
  assert.match(css, /\.admin-header\s*\{[^}]*grid-template-columns:\s*1fr auto 1fr/);
  assert.match(css, /\.admin-stats\s*\{[^}]*background:\s*var\(--navy\)/);
  assert.match(css, /@media \(max-width:\s*620px\)[\s\S]*\.admin-price-grid\s*\{[^}]*grid-template-columns:\s*1fr/);
  assert.match(css, /\.admin-price-grid\s*\{[^}]*overflow-y:\s*auto[^}]*contain:\s*layout paint/);
  assert.match(css, /@media \(max-width:\s*620px\)[\s\S]*\.admin-price-grid\s*\{[^}]*height:\s*min\(64svh,\s*640px\)[^}]*max-height:\s*none/);
  assert.match(css, /@media \(max-width:\s*620px\)[\s\S]*\.admin-toolbar\s*\{[^}]*position:\s*sticky/);
  assert.match(css, /\.people-list\s*\{[^}]*max-height:\s*min\(72vh,\s*760px\)[^}]*overflow-y:\s*auto/);
  assert.match(css, /@media \(max-width:\s*620px\)[\s\S]*\.people-list\s*\{[^}]*max-height:\s*min\(68svh,\s*640px\)/);
  assert.match(css, /@media \(max-width:\s*620px\)[\s\S]*\.person-intents\s*\{[^}]*max-height:\s*none[^}]*overflow:\s*visible/);
  assert.match(css, /\.person-contact-panel \.intent-contact b\s*\{[^}]*overflow-wrap:\s*anywhere/);
  assert.doesNotMatch(admin, /resetPasswordForEmail|PASSWORD_RECOVERY|updateUser\(\{ password:|Criar ou redefinir senha|Visualizar demonstração|Modo demonstração|demoMode|demoIntents/);
});

test("catalog provides flexible prices, full-screen gallery and timed pre-reservation flow", async () => {
  const catalog = await read("app/Catalog.tsx");
  const css = await read("app/globals.css");
  assert.match(catalog, /Abrir galeria/);
  assert.match(catalog, /role="dialog" aria-modal="true" aria-labelledby="gallery-title"/);
  assert.match(catalog, /aria-label="Fechar galeria"/);
  assert.match(catalog, /focusable\[0\]\?\.focus/);
  assert.match(catalog, /modalTriggerRef\.current\.focus/);
  assert.match(catalog, /event\.key !== "Tab"/);
  assert.match(catalog, /submittingRef\.current/);
  assert.match(catalog, /phoneDigits\.length < 8/);
  assert.match(catalog, /className="form-error" role="alert"/);
  assert.match(catalog, /setFormError\("Informe um WhatsApp válido, com DDD\."\)/);
  assert.match(catalog, /mobile-menu-toggle/);
  assert.match(catalog, /aria-controls="mobile-menu"/);
  assert.match(catalog, /aria-label=\{mobileMenuOpen \? "Fechar menu" : "Abrir menu"\}/);
  assert.match(catalog, /href="#conteudo-principal" onClick=\{\(event\) => navigateToSection\(event, "conteudo-principal"\)\}><small>01<\/small>A exposição/);
  assert.match(catalog, /href="#conteudo-principal" onClick=\{\(event\) => navigateToSection\(event, "conteudo-principal"\)\}><small>01<\/small><span>A exposição/);
  assert.match(catalog, /Parceiros desta edição/);
  assert.match(catalog, /className="admin-menu-link" href="#admin"/);
  assert.match(catalog, /price_cents/);
  assert.match(catalog, /submit_pre_reservation/);
  assert.match(catalog, /Pré-reserva temporária/);
  assert.match(catalog, /sem pagamento online/i);
  assert.match(catalog, /extra_contribution_cents/);
  assert.match(catalog, /release_expired_pre_reservations/);
  assert.match(catalog, /ReservationCountdown/);
  assert.match(catalog, /purchase_context/);
  assert.match(catalog, /Hotel Florença/);
  assert.match(catalog, /const holdMinutes = purchaseContext === "outside" \? 24 \* 60 : 30/);
  assert.match(catalog, /hold_minutes: holdMinutes/);
  assert.match(catalog, /De 11 a 17 de setembro/);
  assert.match(catalog, /24 horas · Basílica de Americana/);
  assert.match(catalog, /Confirmar pré-reserva por.*24 horas.*30 min/);
  assert.match(catalog, /allowNotifications/);
  assert.match(catalog, /reservation-toast/);
  assert.doesNotMatch(catalog, /className="numbers"/);
  assert.match(catalog, /renderFloatingCart\("gallery"\)/);
  assert.match(catalog, /className="selection-bag-icon"/);
  assert.doesNotMatch(catalog, /MAX_BID|type="number"/);
  assert.doesNotMatch(catalog, /fallbackWorks/);
  assert.match(css, /\.gallery-overlay\s*\{[^}]*position:\s*fixed/);
  assert.match(catalog, /IntersectionObserver/);
  assert.match(catalog, /requestAnimationFrame/);
  assert.match(catalog, /target\.classList\.add\("is-visible", "anchor-target"\)/);
  assert.match(css, /\[data-reveal\]\.anchor-target\s*\{[^}]*transform:\s*none;[^}]*transition:\s*none/);
  assert.match(catalog, /target\.scrollIntoView\(\{ behavior: "smooth", block: "start" \}\)/);
  assert.match(catalog, /useState<CatalogFilter>\("available"\)/);
  assert.match(catalog, /Em exposição <small>\{availableCount\}<\/small>/);
  assert.match(catalog, /reservableCount/);
  assert.match(catalog, /pré-reservas liberadas/);
  assert.match(catalog, /Aguardando valor/);
  assert.match(catalog, /Obra indisponível/);
  assert.match(catalog, /Corrigir dados e revisar seleção/);
  assert.match(catalog, /inputMode="decimal"/);
  assert.match(catalog, /parseOfferCents/);
  assert.match(catalog, /RESERVATION_STORAGE_KEY/);
  assert.match(catalog, /Prazo e conclusão/);
  assert.match(catalog, /Preparar cópia por e-mail/);
  assert.doesNotMatch(catalog, /mail\.google\.com|Abrir confirmação no Gmail/);
  assert.match(catalog, /<ArtworkExperience3D/);
  assert.match(catalog, /CURATED_ARTWORKS/);
  assert.match(catalog, /<ArtworkPhoto work=\{work\}/);
  assert.doesNotMatch(catalog, /button-view-3d|<span>Detalhes & 3D<\/span>/);
  assert.match(catalog, /Abrir experiência 3D de/);
  assert.match(catalog, /<span className="view-work">Abrir experiência 3D<\/span>/);
  assert.doesNotMatch(css, /\.button-view-3d/);
  assert.doesNotMatch(catalog, /[→↗↑↓←]/);
  assert.match(css, /\.gallery-grid\s*\{[^}]*grid-template-columns:\s*repeat\(3/);
  assert.match(css, /@media \(max-width:\s*1200px\)[\s\S]*\.gallery-grid\s*\{[^}]*grid-template-columns:\s*repeat\(3/);
  assert.match(css, /@media \(max-width:\s*950px\)[\s\S]*\.gallery-grid\s*\{[^}]*grid-template-columns:\s*repeat\(2/);
  assert.match(css, /@media \(max-width:\s*620px\)[\s\S]*\.gallery-grid\s*\{[^}]*grid-template-columns:\s*1fr/);
  assert.match(css, /\.artwork-photo\s*\{[^}]*object-fit:\s*contain/);
  assert.match(css, /#acervo\s*\{[^}]*scroll-margin-top:\s*-52px/);
  assert.match(css, /#doacao\s*\{[^}]*scroll-margin-top:\s*120px/);
  assert.match(css, /@media \(max-width:\s*950px\)[\s\S]*?#acervo\s*\{[^}]*scroll-margin-top:\s*-50px/);
  assert.match(css, /@media \(max-width:\s*620px\)[\s\S]*?#acervo\s*\{[^}]*scroll-margin-top:\s*-55px/);
  assert.match(css, /@media \(max-width:\s*620px\)[\s\S]*?#doacao\s*\{[^}]*scroll-margin-top:\s*24px/);
  assert.match(css, /\.how-section\s*\{[^}]*min-height:\s*100svh/);
  assert.match(css, /\.donation-section\s*\{[^}]*margin:\s*clamp\(72px,9vw,132px\) auto 120px/);
  assert.match(css, /\.pix-pending\s*\{[^}]*min-width:\s*0[^}]*overflow-wrap:\s*anywhere/);
  assert.match(css, /@media \(max-width:\s*1100px\)[\s\S]*\.donation-pix-card\s*\{[^}]*flex-direction:\s*column[^}]*align-items:\s*stretch/);
  assert.match(css, /\.view-work\s*\{[^}]*display:\s*inline-flex/);
  assert.match(css, /\.gallery-close\s*\{[^}]*position:\s*fixed/);
  assert.match(css, /\.modal-close\.detail-close\s*\{[^}]*position:\s*fixed/);
  assert.match(css, /@media \(max-width:\s*620px\)[\s\S]*\.ambient-audio-button\s*\{[^}]*width:\s*37px;[^}]*min-width:\s*37px/);
  assert.match(css, /@media \(max-width:\s*370px\)[\s\S]*\.site-header\s*\{[^}]*padding-inline:\s*10px/);
  assert.match(css, /\.work-image\.navy,[^}]*\{\s*background:\s*transparent/);
  assert.match(css, /aspect-ratio:\s*var\(--artwork-aspect/);
  assert.match(css, /\.arrow-icon::before/);
  assert.match(css, /\.arrow-icon::before\s*\{[^}]*transform:\s*rotate\(45deg\)/);
  assert.match(css, /\.floating-cart\s*\{[^}]*position:\s*fixed/);
  assert.match(css, /\.selection-bag-icon::before/);
  assert.match(css, /prefers-reduced-motion:\s*reduce/);
  assert.match(css, /position:\s*sticky;\s*top:\s*0/);
  assert.match(css, /\.mobile-menu-toggle,\.mobile-menu\s*\{[^}]*display:\s*none/);
  assert.match(css, /\.menu-open \.mobile-menu\s*\{[^}]*display:\s*block/);
  assert.match(css, /\.mobile-menu nav a\s*\{[^}]*grid-template-columns:\s*34px minmax\(0,1fr\) 18px/);
  assert.match(css, /\.mobile-menu nav a::after/);
  assert.match(css, /\.mobile-menu nav span\s*\{[^}]*clamp\(18px,4\.8vw,21px\)/);
});

test("all 84 supplied catalog slots use the real local artwork images and interactive 3D", async () => {
  const images = await read("app/artworkImages.ts");
  const adjustments = await read("app/artworkAdjustments.ts");
  const experience = await read("app/ArtworkExperience3D.tsx");
  assert.match(images, /length: 84/);
  assert.match(images, /Imagem fornecida pela organização do Vernissage 2026/);
  assert.match(images, /`\/artworks-clean\/\$\{filename\}\.webp`/);
  assert.match(experience, /pointerdown/);
  assert.match(experience, /pointermove/);
  assert.match(experience, /touch-action:\s*pan-y|canvas\.dataset\.rotation/);
  assert.match(experience, /scrub:\s*0\.35/);
  assert.match(experience, /new THREE\.TextureLoader\(\)\.loadAsync\(reference\.imageUrl\)/);
  assert.match(experience, /makeArtworkBackCanvas\(work, textureImage\)/);
  assert.match(experience, /globalCompositeOperation = "destination-in"/);
  assert.match(experience, /frontTexture\.flipY\s*=\s*true/);
  assert.match(experience, /backTexture\.flipY\s*=\s*true/);
  assert.match(experience, /makeSilhouetteOutline/);
  assert.match(experience, /const smoothingRadius = 4/);
  assert.match(experience, /makeDepthShellGeometry/);
  assert.match(experience, /geometry\.computeVertexNormals\(\)/);
  assert.match(experience, /product\.rotation\.z = THREE\.MathUtils\.degToRad\(uprightRotationDegrees\)/);
  for (const slot of [38, 43, 59, 66, 79, 81, 83]) assert.match(adjustments, new RegExp(`\\b${slot}:`));
  assert.match(experience, /depthShell\.name = "SilhouetteDepth"/);
  assert.match(experience, /model\.position\.sub\(centeredPivot\)/);
  assert.match(experience, /className="experience-guide"/);
  assert.match(experience, /Toque ou arraste para girar/);
  assert.match(experience, /className="experience-zoom"/);
  assert.match(experience, /useWheelZoom/);
  assert.match(experience, /autoYaw \+= elapsed/);
  assert.match(experience, /Explore frente, espessura e verso · use os controles para ampliar/);
  assert.doesNotMatch(experience, /artist|technique|Artista|Técnica/);
  assert.doesNotMatch(experience, /frontTexture\.rotation/);
  assert.match(experience, /requestAnimationFrame\(animateIdle\)/);
});

test("database migration installs the 84-work catalog and protected price control", async () => {
  const migration = await read("supabase/migrations/20260815211500_real_catalog_and_admin_prices.sql");
  const correction = await read("supabase/migrations/20260816024500_catalog_prices_and_payment_context.sql");
  assert.match(migration, /for artwork_number in 1\.\.84/);
  assert.match(migration, /admin_update_artwork_price/);
  assert.match(migration, /52000/);
  assert.match(migration, /3000000/);
  assert.match(migration, /is_basilica_admin/);
  assert.match(correction, /price_cents is null/);
  assert.match(correction, /when id = 1 then 52000 else null/);
  const availability = await read("supabase/migrations/20260816033000_admin_restore_artwork_availability.sql");
  assert.match(availability, /admin_set_artwork_available/);
  assert.match(availability, /status = 'available'/);
  assert.match(availability, /reserved_until = null/);
  assert.match(availability, /is_basilica_admin/);
});

test("reservation notification and donation callout are explicit but respectful", async () => {
  const countdown = await read("app/ReservationCountdown.tsx");
  const donation = await read("app/DonationSection.tsx");
  const css = await read("app/globals.css");
  assert.match(countdown, /Notification\.requestPermission/);
  assert.match(countdown, /remaining <= 5 \* 60/);
  assert.match(countdown, /const hours = Math\.floor\(remaining \/ 3600000\)/);
  assert.match(countdown, /purchaseContext === "outside"/);
  assert.match(countdown, /antes do fim das 24 horas/);
  assert.match(donation, /donation-attention-button/);
  assert.match(donation, /qr-code-slot/);
  assert.match(donation, /qr-doacao-pix\.png/);
  assert.match(donation, /Escaneie pelo aplicativo do seu banco/);
  assert.match(css, /@keyframes donation-pulse/);
  assert.match(css, /scroll-padding-top:\s*96px/);
  assert.match(css, /scroll-padding-top:\s*75px/);
});

test("3D presentation preserves each artwork's own frame and silhouette", async () => {
  const experience = await read("app/ArtworkExperience3D.tsx");
  assert.doesNotMatch(experience, /goldFrameMaterial/);
  assert.match(experience, /else object\.visible = false/);
});

test("production metadata and hosting configuration are preserved", async () => {
  const layout = await read("app/layout.tsx");
  const hosting = JSON.parse(await read(".openai/hosting.json"));
  assert.match(layout, /Arte pela Basílica/);
  assert.match(layout, /og\.png/);
  assert.match(layout, /metadataBase/);
  assert.match(layout, /canonical/);
  assert.equal(hosting.project_id, "appgprj_6a69ecc5b8048191af285f10c3a452f8");
});

test("GitHub Pages builds the complete client application under its repository path", async () => {
  const pagesConfig = await read("vite.pages.config.ts");
  const pagesEntry = await read("github-pages/main.tsx");
  const pagesHtml = await read("github-pages/index.html");
  const workflow = await read(".github/workflows/pages.yml");
  const assets = await read("app/publicAsset.ts");
  assert.match(pagesConfig, /\/arte-pela-basilica-2026\//);
  assert.match(pagesConfig, /publicDir:\s*"\.\.\/public"/);
  assert.match(pagesEntry, /import Home from "\.\.\/app\/page"/);
  assert.match(pagesHtml, /id="root"/);
  assert.doesNotMatch(pagesHtml, /window\.location\.replace|http-equiv="refresh"/);
  assert.match(workflow, /npm run build:pages/);
  assert.match(workflow, /path:\s*dist-pages/);
  assert.match(assets, /meta\[name="public-base"\]/);
});
