// Generated from The Metropolitan Museum of Art Open Access API.
// Every image below was returned with isPublicDomain=true.
export type CuratedArtworkImage = {
  slot: number; museumId: number; title: string; artist: string; date: string;
  imageUrl: string; thumbnailUrl: string; sourceUrl: string; license: string;
};

export const CURATED_ARTWORKS: CuratedArtworkImage[] = [
  {
    "slot": 1,
    "museumId": 453351,
    "title": "\"The Angel Gabriel meets 'Amr ibn Zaid (the Shepherd)\", Folio from a Siyer-i Nebi (the Life of the Prophet)",
    "artist": "Mustafa ibn Vali",
    "date": "ca. 1595",
    "imageUrl": "/artworks/01.jpg",
    "thumbnailUrl": "/artworks/01.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/453351",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 2,
    "museumId": 453183,
    "title": "The House of Bijapur",
    "artist": "Kamal Muhammad",
    "date": "ca. 1680",
    "imageUrl": "/artworks/02.jpg",
    "thumbnailUrl": "/artworks/02.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/453183",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 3,
    "museumId": 451023,
    "title": "The Lovers",
    "artist": "Riza-yi 'Abbasi",
    "date": "dated 1039 AH/1630 CE",
    "imageUrl": "/artworks/03.jpg",
    "thumbnailUrl": "/artworks/03.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/451023",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 4,
    "museumId": 453336,
    "title": "A Stallion",
    "artist": "Habiballah of Sava",
    "date": "ca. 1601–6",
    "imageUrl": "/artworks/04.jpg",
    "thumbnailUrl": "/artworks/04.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/453336",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 5,
    "museumId": 451725,
    "title": "\"The Concourse of the Birds\", Folio 11r from a Mantiq al-Tayr (Language of the Birds)",
    "artist": "Habiballah of Sava",
    "date": "ca. 1600",
    "imageUrl": "/artworks/05.jpg",
    "thumbnailUrl": "/artworks/05.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/451725",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 6,
    "museumId": 910555,
    "title": "The Thirty-Six Poetic Immortals",
    "artist": "Studio of Kano Takanobu",
    "date": "early 17th century",
    "imageUrl": "/artworks/06.jpg",
    "thumbnailUrl": "/artworks/06.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/910555",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 7,
    "museumId": 451268,
    "title": "\"Akbar With Lion and Calf\", Folio from the Shah Jahan Album",
    "artist": "Govardhan",
    "date": "verso: ca. 1630; recto: ca. 1530–50",
    "imageUrl": "/artworks/07.jpg",
    "thumbnailUrl": "/artworks/07.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/451268",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 8,
    "museumId": 456949,
    "title": "Great Indian Fruit Bat",
    "artist": "Bhawani Das",
    "date": "ca. 1777–82",
    "imageUrl": "/artworks/08.jpg",
    "thumbnailUrl": "/artworks/08.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/456949",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 9,
    "museumId": 544502,
    "title": "Ceiling painting from the palace of Amenhotep III",
    "artist": "Artista desconhecido",
    "date": "ca. 1386–1347 BCE",
    "imageUrl": "/artworks/09.jpg",
    "thumbnailUrl": "/artworks/09.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/544502",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 10,
    "museumId": 435641,
    "title": "Madonna and Child",
    "artist": "Giovanni Bellini",
    "date": "late 1480s",
    "imageUrl": "/artworks/10.jpg",
    "thumbnailUrl": "/artworks/10.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/435641",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 11,
    "museumId": 436573,
    "title": "Cardinal Fernando Niño de Guevara (1541–1609)",
    "artist": "El Greco (Domenikos Theotokopoulos)",
    "date": "ca. 1600",
    "imageUrl": "/artworks/11.jpg",
    "thumbnailUrl": "/artworks/11.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/436573",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 12,
    "museumId": 437769,
    "title": "Clothing the Naked",
    "artist": "Michiel Sweerts",
    "date": "ca. 1661",
    "imageUrl": "/artworks/12.jpg",
    "thumbnailUrl": "/artworks/12.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/437769",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 13,
    "museumId": 436440,
    "title": "Cottage Children (The Wood Gatherers)",
    "artist": "Thomas Gainsborough",
    "date": "1787",
    "imageUrl": "/artworks/13.jpg",
    "thumbnailUrl": "/artworks/13.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/436440",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 14,
    "museumId": 437900,
    "title": "Comtesse de la Châtre (Marie Charlotte Louise Perrette Aglaé Bontemps, 1762–1848)",
    "artist": "Elisabeth Louise Vigée Le Brun",
    "date": "1789",
    "imageUrl": "/artworks/14.jpg",
    "thumbnailUrl": "/artworks/14.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/437900",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 15,
    "museumId": 438814,
    "title": "The Abduction of Rebecca",
    "artist": "Eugène Delacroix",
    "date": "1846",
    "imageUrl": "/artworks/15.jpg",
    "thumbnailUrl": "/artworks/15.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/438814",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 16,
    "museumId": 250939,
    "title": "Wall painting on black ground: landscape, from the imperial villa at Boscotrecase",
    "artist": "Roman, Pompeian",
    "date": "last decade of the 1st century BCE",
    "imageUrl": "/artworks/16.jpg",
    "thumbnailUrl": "/artworks/16.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/250939",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 17,
    "museumId": 247009,
    "title": "Wall painting from Room H of the Villa of P. Fannius Synistor at Boscoreale",
    "artist": "Roman",
    "date": "ca. 50–40 BCE",
    "imageUrl": "/artworks/17.jpg",
    "thumbnailUrl": "/artworks/17.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/247009",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 18,
    "museumId": 437326,
    "title": "Blind Orion Searching for the Rising Sun",
    "artist": "Nicolas Poussin",
    "date": "1658",
    "imageUrl": "/artworks/18.jpg",
    "thumbnailUrl": "/artworks/18.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/437326",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 19,
    "museumId": 435853,
    "title": "The Coronation of the Virgin",
    "artist": "Annibale Carracci",
    "date": "after 1595",
    "imageUrl": "/artworks/19.jpg",
    "thumbnailUrl": "/artworks/19.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/435853",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 20,
    "museumId": 437455,
    "title": "The Holy Family with Saints Anne and Catherine of Alexandria",
    "artist": "Jusepe de Ribera (called Lo Spagnoletto)",
    "date": "1648",
    "imageUrl": "/artworks/20.jpg",
    "thumbnailUrl": "/artworks/20.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/437455",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 21,
    "museumId": 437609,
    "title": "The Holy Family with the Young Saint John the Baptist",
    "artist": "Andrea del Sarto (Andrea d'Agnolo)",
    "date": "ca. 1528",
    "imageUrl": "/artworks/21.jpg",
    "thumbnailUrl": "/artworks/21.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/437609",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 22,
    "museumId": 436323,
    "title": "Marie Emilie Coignet de Courson (1716–1806) with a Dog",
    "artist": "Jean Honoré Fragonard",
    "date": "ca. 1769",
    "imageUrl": "/artworks/22.jpg",
    "thumbnailUrl": "/artworks/22.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/436323",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 23,
    "museumId": 437891,
    "title": "Mars and Venus United by Love",
    "artist": "Paolo Veronese (Paolo Caliari)",
    "date": "1570s",
    "imageUrl": "/artworks/23.jpg",
    "thumbnailUrl": "/artworks/23.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/437891",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 24,
    "museumId": 435851,
    "title": "The Meditation on the Passion",
    "artist": "Vittore Carpaccio",
    "date": "ca. 1490",
    "imageUrl": "/artworks/24.jpg",
    "thumbnailUrl": "/artworks/24.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/435851",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 25,
    "museumId": 436244,
    "title": "Virgin and Child with Saint Anne",
    "artist": "Albrecht Dürer",
    "date": "probably 1519",
    "imageUrl": "/artworks/25.jpg",
    "thumbnailUrl": "/artworks/25.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/436244",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 26,
    "museumId": 436851,
    "title": "Elizabeth Farren (born about 1759, died 1829), Later Countess of Derby",
    "artist": "Sir Thomas Lawrence",
    "date": "1790",
    "imageUrl": "/artworks/26.jpg",
    "thumbnailUrl": "/artworks/26.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/436851",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 27,
    "museumId": 437447,
    "title": "Captain George K. H. Coussmaker (1759–1801)",
    "artist": "Sir Joshua Reynolds",
    "date": "1782",
    "imageUrl": "/artworks/27.jpg",
    "thumbnailUrl": "/artworks/27.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/437447",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 28,
    "museumId": 439933,
    "title": "Lute Player",
    "artist": "Valentin de Boulogne",
    "date": "ca. 1625–26",
    "imageUrl": "/artworks/28.jpg",
    "thumbnailUrl": "/artworks/28.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/439933",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 29,
    "museumId": 247008,
    "title": "Wall painting from the west wall of Room L of the Villa of P. Fannius Synistor at Boscoreale",
    "artist": "Roman",
    "date": "ca. 50–40 BCE",
    "imageUrl": "/artworks/29.jpg",
    "thumbnailUrl": "/artworks/29.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/247008",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 30,
    "museumId": 656430,
    "title": "Portrait of Yun Dongseom (1710–1795)",
    "artist": "Unidentified artist",
    "date": "ca. 1790–1805",
    "imageUrl": "/artworks/30.jpg",
    "thumbnailUrl": "/artworks/30.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/656430",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 31,
    "museumId": 50486,
    "title": "Bamboo in the Wind",
    "artist": "Yi Jeong (artist name: Taneun)",
    "date": "early 17th century",
    "imageUrl": "/artworks/31.jpg",
    "thumbnailUrl": "/artworks/31.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/50486",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 32,
    "museumId": 437329,
    "title": "The Abduction of the Sabine Women",
    "artist": "Nicolas Poussin",
    "date": "probably 1633–34",
    "imageUrl": "/artworks/32.jpg",
    "thumbnailUrl": "/artworks/32.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/437329",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 33,
    "museumId": 437826,
    "title": "Venus and Adonis",
    "artist": "Titian (Tiziano Vecellio)",
    "date": "1550s",
    "imageUrl": "/artworks/33.jpg",
    "thumbnailUrl": "/artworks/33.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/437826",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 34,
    "museumId": 437549,
    "title": "Wheat Fields",
    "artist": "Jacob van Ruisdael",
    "date": "ca. 1670",
    "imageUrl": "/artworks/34.jpg",
    "thumbnailUrl": "/artworks/34.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/437549",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 35,
    "museumId": 435728,
    "title": "The Last Communion of Saint Jerome",
    "artist": "Botticelli (Alessandro di Mariano Filipepi)",
    "date": "early 1490s",
    "imageUrl": "/artworks/35.jpg",
    "thumbnailUrl": "/artworks/35.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/435728",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 36,
    "museumId": 438754,
    "title": "Madonna and Child",
    "artist": "Duccio di Buoninsegna",
    "date": "ca. 1290–1300",
    "imageUrl": "/artworks/36.jpg",
    "thumbnailUrl": "/artworks/36.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/438754",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 37,
    "museumId": 451270,
    "title": "\"Shah Jahan on a Terrace, Holding a Pendant Set With His Portrait\", Folio from the Shah Jahan Album",
    "artist": "Chitarman",
    "date": "recto: dated 1627–28; verso: ca. 1530–50",
    "imageUrl": "/artworks/37.jpg",
    "thumbnailUrl": "/artworks/37.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/451270",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 38,
    "museumId": 544442,
    "title": "Sphinx of Hatshepsut",
    "artist": "Artista desconhecido",
    "date": "ca. 1473–1458 BCE",
    "imageUrl": "/artworks/38.jpg",
    "thumbnailUrl": "/artworks/38.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/544442",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 39,
    "museumId": 436964,
    "title": "Young Lady in 1866",
    "artist": "Edouard Manet",
    "date": "1866",
    "imageUrl": "/artworks/39.jpg",
    "thumbnailUrl": "/artworks/39.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/436964",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 40,
    "museumId": 436840,
    "title": "Self-Portrait with Two Pupils, Marie Gabrielle Capet (1761–1818) and Marie Marguerite Carraux de Rosemond (1765–1788)",
    "artist": "Adélaïde Labille-Guiard",
    "date": "1785",
    "imageUrl": "/artworks/40.jpg",
    "thumbnailUrl": "/artworks/40.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/436840",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 41,
    "museumId": 438605,
    "title": "The Crucifixion",
    "artist": "Pietro Lorenzetti",
    "date": "1340s",
    "imageUrl": "/artworks/41.jpg",
    "thumbnailUrl": "/artworks/41.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/438605",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 42,
    "museumId": 437175,
    "title": "Virgin and Child",
    "artist": "Bartolomé Estebán Murillo",
    "date": "1670s",
    "imageUrl": "/artworks/42.jpg",
    "thumbnailUrl": "/artworks/42.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/437175",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 43,
    "museumId": 437879,
    "title": "Study of a Young Woman",
    "artist": "Johannes Vermeer",
    "date": "ca. 1665–67",
    "imageUrl": "/artworks/43.jpg",
    "thumbnailUrl": "/artworks/43.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/437879",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 44,
    "museumId": 436658,
    "title": "Hermann von Wedigh III (died 1560)",
    "artist": "Hans Holbein the Younger",
    "date": "1532",
    "imageUrl": "/artworks/44.jpg",
    "thumbnailUrl": "/artworks/44.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/436658",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 45,
    "museumId": 437423,
    "title": "The Immaculate Conception",
    "artist": "Guido Reni",
    "date": "1627",
    "imageUrl": "/artworks/45.jpg",
    "thumbnailUrl": "/artworks/45.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/437423",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 46,
    "museumId": 436918,
    "title": "Venus and Cupid",
    "artist": "Lorenzo Lotto",
    "date": "1520s",
    "imageUrl": "/artworks/46.jpg",
    "thumbnailUrl": "/artworks/46.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/436918",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 47,
    "museumId": 437869,
    "title": "Juan de Pareja (ca. 1608–1670)",
    "artist": "Velázquez (Diego Rodríguez de Silva y Velázquez)",
    "date": "1650",
    "imageUrl": "/artworks/47.jpg",
    "thumbnailUrl": "/artworks/47.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/437869",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 48,
    "museumId": 437971,
    "title": "The Young Virgin",
    "artist": "Francisco de Zurbarán",
    "date": "ca. 1632–33",
    "imageUrl": "/artworks/48.jpg",
    "thumbnailUrl": "/artworks/48.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/437971",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 49,
    "museumId": 436105,
    "title": "The Death of Socrates",
    "artist": "Jacques Louis David",
    "date": "1787",
    "imageUrl": "/artworks/49.jpg",
    "thumbnailUrl": "/artworks/49.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/436105",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 50,
    "museumId": 436106,
    "title": "Antoine Laurent Lavoisier (1743–1794) and Marie Anne Lavoisier (Marie Anne Pierrette Paulze, 1758–1836)",
    "artist": "Jacques Louis David",
    "date": "1788",
    "imageUrl": "/artworks/50.jpg",
    "thumbnailUrl": "/artworks/50.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/436106",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 51,
    "museumId": 436792,
    "title": "The Crucifixion with Saints and a Donor",
    "artist": "Joos van Cleve",
    "date": "ca. 1520",
    "imageUrl": "/artworks/51.jpg",
    "thumbnailUrl": "/artworks/51.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/436792",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 52,
    "museumId": 435802,
    "title": "Portrait of a Young Man",
    "artist": "Bronzino (Agnolo di Cosimo di Mariano)",
    "date": "1530s",
    "imageUrl": "/artworks/52.jpg",
    "thumbnailUrl": "/artworks/52.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/435802",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 53,
    "museumId": 437056,
    "title": "Tommaso di Folco Portinari (1428–1501); Maria Portinari (Maria Maddalena Baroncelli, born 1456)",
    "artist": "Hans Memling",
    "date": "ca. 1470",
    "imageUrl": "/artworks/53.jpg",
    "thumbnailUrl": "/artworks/53.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/437056",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 54,
    "museumId": 679844,
    "title": "Fish Market",
    "artist": "Joachim Beuckelaer",
    "date": "1568",
    "imageUrl": "/artworks/54.jpg",
    "thumbnailUrl": "/artworks/54.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/679844",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 55,
    "museumId": 438815,
    "title": "Madame Georges Charpentier (Marguerite-Louise Lemonnier, 1848–1904) and Her Children, Georgette-Berthe (1872–1945) and Paul-Emile-Charles (1875–1895)",
    "artist": "Auguste Renoir",
    "date": "1878",
    "imageUrl": "/artworks/55.jpg",
    "thumbnailUrl": "/artworks/55.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/438815",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 56,
    "museumId": 436575,
    "title": "View of Toledo",
    "artist": "El Greco (Domenikos Theotokopoulos)",
    "date": "ca. 1599–1600",
    "imageUrl": "/artworks/56.jpg",
    "thumbnailUrl": "/artworks/56.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/436575",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 57,
    "museumId": 634108,
    "title": "The Dream of the Shepherd (Der Traum des Hirten)",
    "artist": "Ferdinand Hodler",
    "date": "1896",
    "imageUrl": "/artworks/57.jpg",
    "thumbnailUrl": "/artworks/57.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/634108",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 58,
    "museumId": 436603,
    "title": "Samson Captured by the Philistines",
    "artist": "Guercino (Giovanni Francesco Barbieri)",
    "date": "1619",
    "imageUrl": "/artworks/58.jpg",
    "thumbnailUrl": "/artworks/58.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/436603",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 59,
    "museumId": 437532,
    "title": "Rubens, Helena Fourment (1614–1673), and Their Son Frans (1633–1678)",
    "artist": "Peter Paul Rubens",
    "date": "ca. 1635",
    "imageUrl": "/artworks/59.jpg",
    "thumbnailUrl": "/artworks/59.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/437532",
    "license": "Public Domain — The Metropolitan Museum of Art"
  },
  {
    "slot": 60,
    "museumId": 435621,
    "title": "Joan of Arc",
    "artist": "Jules Bastien-Lepage",
    "date": "1879",
    "imageUrl": "/artworks/60.jpg",
    "thumbnailUrl": "/artworks/60.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/435621",
    "license": "Public Domain — The Metropolitan Museum of Art"
  }
];
